name: Deploy docs

# executa o deploy sempre que houver um push na branch main
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps: # passos
      - name: Checkout
        uses: actions/checkout@v4

        # setup do node
      - name: Setup Node.js
      - uses: actions/setup-node@v3
        with: 
          node-version: 18

      # para instalar somente a s dependências de produção
      - run: npm ci

      # executa a build que foi configurada no turbo
      - run: npm run build

      - name: Deploy storybook
        working-directory: ./packages/docs
        run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}